version: '2'
services:
  icinga2:
    image: korekontrol/docker-icinga2:latest
    restart: on-failure:5
    hostname: icinga2
    env_file:
      - secrets_sql.env
    environment:
      - ICINGA2_FEATURE_GRAPHITE=1
      - ICINGA2_FEATURE_GRAPHITE_HOST=graphite
      - ICINGA2_FEATURE_GRAPHITE_PORT=2003
      - ICINGA2_FEATURE_GRAPHITE_URL=http://graphite
      #- ICINGAWEB2_ADMIN_USER=icingaadmin
      #- ICINGAWEB2_ADMIN_PASS=icinga
      #- ICINGA2_USER_FULLNAME=Icinga2 Docker Monitoring Instance
      - DEFAULT_MYSQL_HOST=mysql
    volumes:
      - ./data/icinga/cache:/var/cache/icinga2
      - ./data/icinga/certs:/etc/apache2/ssl
      - ./data/icinga/etc/icinga2:/etc/icinga2
      - ./data/icinga/etc/icingaweb2:/etc/icingaweb2
      - ./data/icinga/lib/icinga:/var/lib/icinga2
      - ./data/icinga/lib/php/sessions:/var/lib/php/sessions
      - ./data/icinga/log/apache2:/var/log/apache2
      - ./data/icinga/log/icinga2:/var/log/icinga2
      - ./data/icinga/log/icingaweb2:/var/log/icingaweb2
      - ./data/icinga/log/opsgenie:/var/log/opsgenie
      - ./data/icinga/log/mysql:/var/log/mysql
      - ./data/icinga/spool:/var/spool/icinga2
      # If you want to enable outbound e-mail, create the files
      #  - ./ssmtp/ssmtp.conf
      #  - ./ssmtp/revaliases
      #  and configure to your corresponding mail setup.
      #  See: https://github.com/jjethwa/icinga2#sending-notification-mails
      #- ./ssmtp/revaliases:/etc/ssmtp/revaliases:ro
      #- ./ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
    ports:
      - "80:80"
      - "443:443"
      - "5665:5665"
    depends_on:
      - mysql
      - graphite
  graphite:
    image: graphiteapp/graphite-statsd:1.1.6-1
    restart: on-failure:5
    hostname: graphite
    environment:
      - REDIS_TAGDB=True
      - GRAPHITE_WSGI_PROCESSES=2
      - GRAPHITE_WSGI_THREADS=4
      - MEMCACHE_HOST=memcached:11211
    volumes:
      - ./data/graphite/storage:/opt/graphite/storage
      - ./data/graphite/conf:/opt/graphite/conf
      - ./data/graphite/redis:/var/lib/redis
    ports:
      - "8080:8080"
    depends_on:
      - memcached
  grafana:
    image: grafana/grafana:6.0.1
    environment:
      - GF_BASIC_AUTH_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=1
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./data/grafana/data:/var/lib/grafana
    ports:
      - "8081:3000"
    depends_on:
      - graphite
  mysql:
    image: mariadb:10.1
    command: --innodb-buffer-pool-size=256M --innodb-file-per-table --character_set_server=latin1 --innodb_flush_log_at_trx_commit=2
    env_file:
      - secrets_sql.env
    volumes:
      - ./data/mysql/data:/var/lib/mysql
  memcached:
    image: memcached:1-alpine
    restart: on-failure:5
    command: 'memcached -m 128'
