#!/bin/bash

. /opt/helpers

echo 'Preparing marid'

# adjust icinga api credentials
if [ ! -z "${ICINGAWEB2_ADMIN_USER}" ]; then
  sed -i "s/icinga.user=.*/icinga.user=${ICINGAWEB2_ADMIN_USER}/" /etc/opsgenie/conf/opsgenie-integration.conf
fi
if [ ! -z "${ICINGAWEB2_ADMIN_PASS}" ]; then
  sed -i "s/icinga.password=.*/icinga.password=${ICINGAWEB2_ADMIN_PASS}/" /etc/opsgenie/conf/opsgenie-integration.conf
fi

# chown directories and files that might be coming from volumes
mkdir -p /var/log/opsgenie/marid
chown -R opsgenie:opsgenie /var/log/opsgenie/marid

